### PR TITLE
Add network status to navbar

### LINKED ISSUE #302: Add network status to the 'network' menu as per design
Add the networks as a column in the 'network' tab. Ideally this should be caching and polling in the background so it doesn't block the navigation if a user is trying to flip through quickly.

### PR DESCRIPTION
**Pull request by aureentuluvacal**
Closes #302

### CODE REVIEW

**Review by schpet — CHANGES_REQUESTED** [review]
tried to run this locally but it seemed to go from loading to hitting the root error boundary – not sure what's up here but can you let me know if you need help reproducing this error?

Screen Shot 2022-06-24 at 4 00 42 PM
Screen Shot 2022-06-24 at 4 00 35 PM

**Comment by aureentuluvacal** [comment]
> tried to run this locally but it seemed to go from loading to hitting the root error boundary – not sure what's up here but can you let me know if you need help reproducing this error?
> 
> Screen Shot 2022-06-24 at 4 00 42 PM

@schpet Do you have the `STATUSPAGE_API_KEY` env var set?

**Comment by schpet** [comment]
@aureentuluvacal i do not have the `STATUSPAGE_API_KEY` env var set!

**Review by schpet — APPROVED** [review]
image


lgtm! i think a good future addition would be more isolated error handling but for today this is looking great 👍🏻

**Pull request merged**
