### PR TITLE
Refactor fetchFlips from json export/import to returning Props

### PR DESCRIPTION
**Pull request by codingone21**
- Changed implementation from fetching exported `.json` to fetching actual component format `FlipCellProps[]`. 
- Added a view page in routing, /flipsView for testing. 

Loaded View:
Screen Shot 2022-06-09 at 10 46 12 AM

### CODE REVIEW

**Comment by schpet** [comment]
@codingone21 fyi i should be able to check this out once the build is working again! any instructions on how to run this code? e.g. do i go to localhost:3000/flipsView or something?

**Comment by schpet** [comment]
@codingone21 fyi i should be able to check this out once the build is working again! any instructions on how to run this code? e.g. do i go to localhost:3000/flipsView or something?

**Comment by codingone21** [comment]
> @codingone21 fyi i should be able to check this out once the build is working again! any instructions on how to run this code? e.g. do i go to localhost:3000/flipsView or something?

Thanks and yep! That should be the correct route. I'll also verify once build is working.

**Review by 10thfloor — CHANGES_REQUESTED** [review]
Nice. You can move this file into a `utils` folder as we discussed.

**Comment by codingone21** [comment]
Successfully builds, but errors on loading due to how remix data loading works. LoaderFunction is meant to be use only under /routes. Working on a fix

**Comment by 10thfloor** [comment]
> Successfully builds, but errors on loading due to how remix data loading works. LoaderFunction is meant to be use only under /routes. Working on a fix

Ah so we can get reid of the LoaderFunction and just have this code in a generic function, that we can import anywhere we need (including but not necessarily a LoaderFunction)

**Comment by codingone21** [comment]
> > Successfully builds, but errors on loading due to how remix data loading works. LoaderFunction is meant to be use only under /routes. Working on a fix
> 
> Ah so we can get rid of the LoaderFunction and just have this code in a generic function, that we can import anywhere we need (including but not necessarily a LoaderFunction)

Yep! exactly :) The recent commits changed the loader function to 'fetchFlips', which is just a generic call. We can call this from a loader function for components rendering

**Review by 10thfloor — APPROVED** [review]

**Pull request merged**
