### PR TITLE
Add Tools page to remix app

### LINKED ISSUE #176: [Storybook -> Pages] Tools

### PR DESCRIPTION
**Pull request by joekrill**
- Adds the Tools page implementation to the remix app
- Adjusts the `TutorialCard`'s layout to allow space for 2-line headers
- `SDKCard` and `ToolCard` can take either an `iconSrc` _or_ an known `iconType` (must be one or the other).

Closes #176

### CODE REVIEW

**Comment by alse** [comment]
I was thinking the same @schpet , it would be nice for all the components to only take srcs. Agree that it's subjective, so I'm good with merging as well!

**Comment by joekrill** [comment]
@schpet @alse you're right - simpler is better, this was just overcomplicating things with no real benefit. I'll have some changes up momentarily!

**Review by aureentuluvacal — COMMENTED** [review]
@joekrill the SVGs aren't loading on build. 500 errors for all images.

Also, SDK card star count looks a lil wonky 
image

**Review by schpet — APPROVED** [review]
🤙🏻

**Pull request merged**
